/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocktakeRouteImport } from './routes/stocktake'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OwnersMonthlyRouteImport } from './routes/owners-monthly'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const StocktakeRoute = StocktakeRouteImport.update({
  id: '/stocktake',
  path: '/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersMonthlyRoute = OwnersMonthlyRouteImport.update({
  id: '/owners-monthly',
  path: '/owners-monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/owners-monthly': typeof OwnersMonthlyRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/stocktake': typeof StocktakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/owners-monthly': typeof OwnersMonthlyRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/stocktake': typeof StocktakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/owners-monthly': typeof OwnersMonthlyRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/stocktake': typeof StocktakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/daily'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/monthly'
    | '/owners-monthly'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/stocktake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/daily'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/monthly'
    | '/owners-monthly'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/stocktake'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/daily'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/monthly'
    | '/owners-monthly'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/stocktake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DailyRoute: typeof DailyRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MonthlyRoute: typeof MonthlyRoute
  OwnersMonthlyRoute: typeof OwnersMonthlyRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  StocktakeRoute: typeof StocktakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocktake': {
      id: '/stocktake'
      path: '/stocktake'
      fullPath: '/stocktake'
      preLoaderRoute: typeof StocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners-monthly': {
      id: '/owners-monthly'
      path: '/owners-monthly'
      fullPath: '/owners-monthly'
      preLoaderRoute: typeof OwnersMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DailyRoute: DailyRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MonthlyRoute: MonthlyRoute,
  OwnersMonthlyRoute: OwnersMonthlyRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  StocktakeRoute: StocktakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
